name: Praxis Flush

on:
  push:
    paths:
      - '**.zkc'
      - '**/praxis/**'
      - '.github/workflows/flush.yml'

jobs:
  flush:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install zip
        run: sudo apt-get install zip -y

      - name: Create Praxis Zip
        run: zip -r praxis.zip praxis/ *.zkc

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v-latest
          files: praxis.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
